name: CMake on Linux

on:
  push:
    branches: [ "build-and-export" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} CMakeLists.txt
      run: |
        ls
        mkdir -p ${{github.workspace}}/build
        cmake CMakeLists.txt
    - name: Build
      run: make


